# **PyTorch Tensor Operations**

**Laboratory 5:** *PyTorch Basics*
___

This laboratory explores fundamental tensor operations in PyTorch, including reproducibility through random seeds, NumPy-to-tensor conversion, data type conversion, reshaping, indexing, element-wise operations, and matrix multiplication.

## **Objectives**

By the end of this laboratory, the student should be able to:

- understand basic PyTorch tensor operations;
- manipulate tensors correctly; and
- apply tensor operations in simple computations.

## **Laboratory Problem**

1. Perform Standard Imports

2. Create a function called `set_seed()` that accepts `seed: int` as a parameter, this function must return nothing but just set the seed to a certain value.

3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive), call the `set_seed()` function and use `42` as the seed parameter.

4. Create a tensor "x" from the array above

5. Change the dtype of x from `int32` to `int64`

6. Reshape `x` into a 3x2 tensor** <br> There are several ways to do this.

7. Return the right-hand column of tensor `x`

8. Without changing x, return a tensor of square values of `x`** <br> There are several ways to do this.

9. Create a tensor `y` with the same number of elements as `x`, that can be matrix-multiplied with `x`** <br> Use PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive). Use 42 as seed. <br> Think about what shape it should have to permit matrix multiplication.

10. Find the matrix product of `x` and `y`.

### **Solution:**

**1. Perform Standard Imports**

In [4]:
import torch
import numpy as np


**2. Create a function called `set_seed()` that accepts `seed: int` as a parameter, this function must return nothing but just set the seed to a certain value.**

In [5]:
def set_seed(seed):
    np.random.seed(seed)
    torch.manual_seed(seed)

**3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive), call the `set_seed()` function and use `42` as the seed parameter.**

In [6]:
set_seed(42)
arr = np.random.randint(0, 5, size=6).astype('int32')

assert np.array_equal(arr, np.array([3,4,2,4,4,1])), "Oops"
print(arr)

[3 4 2 4 4 1]


**4. Create a tensor "x" from the array above**

In [7]:
x = torch.from_numpy(arr)
print(x)

tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)


**5. Change the dtype of x from `int32` to `int64`**

In [8]:
print('Old:', x.type())

x = x.type(torch.int64)

print('New:', x.type())

Old: torch.IntTensor
New: torch.LongTensor


**6. Reshape `x` into a 3x2 tensor** <br> There are several ways to do this.

In [9]:
x = x.reshape(3,2)
print(x)

tensor([[3, 4],
        [2, 4],
        [4, 1]])


**7. Return the right-hand column of tensor `x`**

In [10]:
print(x[:,1:])

tensor([[4],
        [4],
        [1]])


**8. Without changing x, return a tensor of square values of `x`** <br> There are several ways to do this.

In [ ]:
print(x.pow(2))
print(x) 

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])
tensor([[3, 4],
        [2, 4],
        [4, 1]])


**9. Create a tensor `y` with the same number of elements as `x`, that can be matrix-multiplied with `x`** <br> Use PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive). Use 42 as seed. <br> Think about what shape it should have to permit matrix multiplication.


In [12]:
set_seed(42)
y = torch.randint(0,5,(2,3))

assert torch.equal(y, torch.tensor([[2, 2, 1],[4, 1, 0]])), "Oops"
print(y)

tensor([[2, 2, 1],
        [4, 1, 0]])


**10. Find the matrix product of `x` and `y`.**

In [13]:
prod = torch.mm(x,y)
prod

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])

## **Reflection**

This laboratory helped me become more familiar with how PyTorch handles numerical data through tensors. I understood more clearly that tensor operations are similar to NumPy but also require careful attention to data types and dimensions. The matrix multiplication activity especially helped me see why tensor shapes are important, since an operation can only be performed when the dimensions are compatible. Learning these basic operations gives me a better foundation for understanding how data and parameters are processed inside neural networks.